### ISSUE TITLE
macOS tr "Illegal byte sequence"

### ISSUE THREAD

**Issue by zhyatt** [guilhermelawless/blake2b-pow-bench#1]
On macOS 10.14.6 when attempting to run the script the following error appears for each hash generation attempt: `tr: Illegal byte sequence`

The solution is to "specify the locale by prepending the `tr` command with `LC_CTYPE=C`" per https://unix.stackexchange.com/questions/45404/why-cant-tr-read-from-dev-urandom-on-osx. This worked for me, but I wasn't sure if or how you'd like this updated.

**Comment by guilhermelawless** [comment]
Your fix worked on linux and windows so I updated the script with it, thanks!
